"""uuid product

Revision ID: 35383c8c5e96
Revises: a58e2ff5a255
Create Date: 2026-01-08 18:06:51.856479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35383c8c5e96'
down_revision: Union[str, Sequence[str], None] = 'a58e2ff5a255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('uuid_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'uuid_id')
    # ### end Alembic commands ###
